In [2]:
import torch

# Variable dengan tipe data tensor

A brief note about tensors and their number of dimensions, and terminology:
- You will sometimes see a 1-dimensional tensor called a vector.
- Likewise, a 2-dimensional tensor is often referred to as a matrix.
- Anything with more than two dimensions is generally just called a tensor

In [16]:
# Membuat tensor 2 dimensi dengan 3 rows dan 4 columns
empty_var = torch.empty(2, 4)
print(empty_var)
print(type(empty_var))

tensor([[2.5961e+20, 6.3013e-10, 2.5642e-09, 4.2098e+21],
        [4.0068e-11, 7.1450e+31, 2.1776e+23, 6.6015e-07]])
<class 'torch.Tensor'>


In [4]:
# Membuat tensor 3 dimensi dengan 2 channel, 3 rows dan 4 columns
random_var = torch.rand(2, 3, 4)
print(random_var)

tensor([[[0.5253, 0.8590, 0.4542, 0.6819],
         [0.8534, 0.3037, 0.7137, 0.4056],
         [0.4821, 0.4062, 0.6276, 0.8302]],

        [[0.4816, 0.4402, 0.8819, 0.0656],
         [0.4039, 0.4057, 0.8656, 0.3438],
         [0.4136, 0.1722, 0.6482, 0.0894]]])


In [5]:
# Membuat tensor dengan nilai 1 berukuran 2, 3, 4
ones_var = torch.ones(2, 3, 4)
print(ones_var)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [6]:
# Variable tensor dengan nilai 0 berukuran 2, 3, 4
zeros_var = torch.zeros(2, 3, 4)
print(zeros_var)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [8]:
# Membuat variabel tensor yang berurutan sejumlah n atau dari x hingga y (bahkan dengan step atau jarak tertentu)
rentang = torch.arange(12, dtype=torch.float32)
print(rentang)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])


In [9]:
rentang2 = torch.arange(0, 12, 2, dtype=torch.float32)
print(rentang2)

tensor([ 0.,  2.,  4.,  6.,  8., 10.])


# Membuat variabel tensor dengan tipe data spesifik

In [14]:
# Membuat tensor dengan tipe data integer
int_var = torch.ones(2, 2, dtype=torch.int)
print(int_var)
print(int_var.dtype)
print(int_var.size())

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
torch.int32
torch.Size([2, 2])


In [17]:
# Membuat tensor dengan tipe data float
float_var = torch.ones(2, 2, dtype=torch.float)
print(float_var)
print(float_var.dtype)
print(float_var.size())

tensor([[1., 1.],
        [1., 1.]])
torch.float32
torch.Size([2, 2])


In [20]:
torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [21]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


# Tensor Shapes

In [23]:
x = torch.empty(2, 3, 4)
print(x.shape)
print(x)

torch.Size([2, 3, 4])
tensor([[[9.2755e-39, 1.0561e-38, 1.0929e-38, 9.9184e-39],
         [9.2755e-39, 8.4490e-39, 1.0102e-38, 9.0919e-39],
         [1.0102e-38, 8.9082e-39, 8.4489e-39, 1.0102e-38]],

        [[1.0561e-38, 1.0286e-38, 1.0653e-38, 1.0469e-38],
         [9.5510e-39, 8.9999e-39, 1.0561e-38, 9.0919e-39],
         [9.9184e-39, 9.0000e-39, 1.0561e-38, 1.0653e-38]]])


In [24]:
empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

torch.Size([2, 3, 4])
tensor([[[0.0000e+00, 1.0561e-38, 7.0295e+28, 6.1949e-04],
         [4.4321e+27, 1.7975e+19, 6.9481e+22, 3.9177e-02],
         [4.7429e+30, 5.1476e+22, 7.9325e+34, 2.8219e+26]],

        [[5.5102e-14, 4.7622e+30, 1.3569e-14, 7.6194e+31],
         [1.7860e+25, 1.8124e+34, 2.6800e+20, 1.9072e+17],
         [1.8318e+25, 4.9719e+22, 7.9325e+34, 2.8219e+26]]])


In [25]:
zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

torch.Size([2, 3, 4])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [26]:
ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

torch.Size([2, 3, 4])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [27]:
rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 3, 4])
tensor([[[0.6128, 0.1519, 0.0453, 0.5035],
         [0.9978, 0.3884, 0.6929, 0.1703],
         [0.1384, 0.4759, 0.7481, 0.0361]],

        [[0.5062, 0.8469, 0.2588, 0.2707],
         [0.4115, 0.6839, 0.0703, 0.5105],
         [0.9451, 0.2359, 0.1979, 0.3327]]])


In [28]:
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])


In [29]:
some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

tensor([ 2,  3,  5,  7, 11, 13, 17, 19])


In [30]:
more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

tensor([[2, 4, 6],
        [3, 6, 9]])


# Tensor Data Type

In [32]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20.
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[12.3902, 15.0541, 16.8179],
        [17.7174, 14.2091, 18.9694]], dtype=torch.float64)
tensor([[12, 15, 16],
        [17, 14, 18]], dtype=torch.int32)


Available data types include:
- torch.bool
- torch.int8
- torch.uint8
- torch.int16
- torch.int32
- torch.int64
- torch.half
- torch.float
- torch.double
- torch.bfloat

# Upcasting and Downcasting a Pytorch Tensor
- An upcasting happens when a lower data type, such as an integer is converted to a higher data type, such as a float.
- A downcasting happens when a higher data type, such as a float is converted to a lower data type, such as an integer

In [3]:
tensor_4 = torch.tensor([[4, 2], [1, 3]], dtype=torch.float64)

print(tensor_4)
# Ouputs- tensor([[4., 2.], [1., 3.]], dtype=torch.float64)

tensor([[4., 2.],
        [1., 3.]], dtype=torch.float64)


In [4]:
tensor_5 = torch.tensor([[4.7, 2.2], [1.4, 7.8]], dtype=torch.int16)

print(tensor_5)
# Ouputs- tensor([[4, 2], [1, 7]], dtype=torch.int16)

tensor([[4, 2],
        [1, 7]], dtype=torch.int16)


C:\Users\wilden\AppData\Local\Temp\ipykernel_20028\1096050098.py:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  tensor_5 = torch.tensor([[4.7, 2.2], [1.4, 7.8]], dtype=torch.int16)


# Creating a Pytorch Tensor from a Numpy Array

In [6]:
import numpy as np
np_tensor = np.array([1, 2, 3, 4])

pytorch_tensor = torch.from_numpy(np_tensor)

print(type(pytorch_tensor))
# Outputs- torch.Tensor

print(pytorch_tensor)
# Outputs- tensor([1, 2, 3, 4])

<class 'torch.Tensor'>
tensor([1, 2, 3, 4], dtype=torch.int32)
