In [1]:
import torch

# Accessing Tensor Elements

In [2]:
tensor = torch.tensor([2, 4, 1, 7, 0, 9])

print(tensor[0])
# Outputs- tensor(2)

print(tensor[3])
# Outputs- tensor(7)

tensor(2)
tensor(7)


In [3]:
tensor = torch.tensor([2, 4, 1, 7, 0, 9])

print(tensor[1 : 5])
# Outputs- tensor([4, 1, 7, 0])

tensor([4, 1, 7, 0])


In [4]:
tensor = torch.tensor([2, 4, 1, 7, 0, 9])

print(tensor[2 : ])
# Outputs- tensor([1, 7, 0, 9])

tensor([1, 7, 0, 9])


In [5]:
tensor = torch.tensor([2, 4, 1, 7, 0, 9])

print(tensor[ : 4])
# Outputs- tensor([2, 4, 1, 7])

tensor([2, 4, 1, 7])


In [6]:
tensor = torch.tensor([2, 4, 1, 7, 0, 9])

print(tensor[ : ])
# Outputs- tensor([2, 4, 1, 7, 0, 9])

tensor([2, 4, 1, 7, 0, 9])


In [7]:
tensor = torch.tensor([[1, 2, 1], [3, 8, 4]])

print(tensor[1])
# Outputs- tensor([3, 8, 4])

tensor([3, 8, 4])


In [8]:
tensor = torch.tensor([[1, 2, 1], [3, 8, 4]])

print(tensor[0][2])
# Outputs- tensor(1)

tensor(1)


# Changing Tensor Elements

In [9]:
tensor = torch.tensor([2, 4, 1, 7, 0, 9])

# assign value 8 to the 0th index in the tensor
tensor[0] = 8

print(tensor)
# Outputs- tensor([8, 4, 1, 7, 0, 9])

tensor([8, 4, 1, 7, 0, 9])


In [10]:
tensor = torch.tensor([[1, 2, 1], [3, 8, 4]])

# assign value 7 at the given index
tensor[0][0] = 7

print(tensor)
# Outputs- tensor([[7, 2, 1], [3, 8, 4]])

tensor([[7, 2, 1],
        [3, 8, 4]])
