# Addition

In [2]:
import torch

In [2]:
tensor_1 = torch.tensor([[1, 2], [1, 3]])
tensor_2 = torch.tensor([[2, 3], [0, 4]])

# 1+2 2+3
# 1+0 3+4

result = tensor_1 + tensor_2
print(result)

tensor([[3, 5],
        [1, 7]])


In [3]:
result_add = torch.add(tensor_1, tensor_2)
print(result_add)

tensor([[3, 5],
        [1, 7]])


In [4]:
result_add = tensor_1.add(tensor_2)
print(result_add)

tensor([[3, 5],
        [1, 7]])


# Subtraction

In [4]:
tensor_1 = torch.tensor([[1, 2], [1, 3]])
tensor_2 = torch.tensor([[4, 6], [5, 1]])

# 1-4 2-6
# 1-5 3-1

result = tensor_1 - tensor_2
print(result)

tensor([[-3, -4],
        [-4,  2]])


In [5]:
tensor_1 = torch.tensor([[1, 2], [1, 3]])
tensor_2 = torch.tensor([[2, 3], [0, 4]])

print(torch.sub(tensor_1, tensor_2))
# Outputs- tensor([[-1, -1], [1, -1]])

print(tensor_1.sub(tensor_2))
# Outputs- tensor([[-1, -1], [1, -1]])

tensor([[-1, -1],
        [ 1, -1]])
tensor([[-1, -1],
        [ 1, -1]])


# Multiplication

In [6]:
tensor_1 = torch.tensor([[1, 2], [1, 3]])
tensor_2 = torch.tensor([[2, 3], [0, 4]])

# 1x2 2x3
# 1x0 3x4

print(tensor_1 * tensor_2)
# Outputs- tensor([[2, 6], [0, 12]])

tensor([[ 2,  6],
        [ 0, 12]])


In [7]:
tensor_1 = torch.tensor([[1, 2], [1, 3]])
tensor_2 = torch.tensor([[2, 3], [0, 4]])

print(torch.mul(tensor_1, tensor_2))
# Outputs- tensor([[2, 6], [0, 12]])

print(tensor_1.mul(tensor_2))
# Outputs- tensor([[2, 6], [0, 12]])

tensor([[ 2,  6],
        [ 0, 12]])
tensor([[ 2,  6],
        [ 0, 12]])


# Division

In [8]:
tensor_1 = torch.tensor([[1, 2], [1, 3]])
tensor_2 = torch.tensor([[2, 3], [0, 4]])

print(tensor_1 / tensor_2)
# Outputs- tensor([[0.5000, 0.6667], [inf, 0.7500]])

tensor([[0.5000, 0.6667],
        [   inf, 0.7500]])


In [9]:
tensor_1 = torch.tensor([[1, 2], [1, 3]])
tensor_2 = torch.tensor([[2, 3], [0, 4]])

print(torch.div(tensor_1, tensor_2))
# Outputs- tensor([[0.5000, 0.6667], [inf, 0.7500]])

print(tensor_1.div(tensor_2))
# Outputs- tensor([[0.5000, 0.6667], [inf, 0.7500]])

tensor([[0.5000, 0.6667],
        [   inf, 0.7500]])
tensor([[0.5000, 0.6667],
        [   inf, 0.7500]])


# Exponent

In [12]:
tensor_1 = torch.tensor([[1, 2], [1, 3]])
tensor_2 = torch.tensor([[2, 3], [0, 4]])

# 1^1 2^3
# 1^0 3^4

print(tensor_1 ** tensor_2)
# Outputs- tensor([[1, 8], [1, 81]])

tensor([[ 1,  8],
        [ 1, 81]])


In [13]:
tensor_1 = torch.tensor([[1, 2], [1, 3]])
tensor_2 = torch.tensor([[2, 3], [0, 4]])

print(torch.pow(tensor_1, tensor_2))
# Outputs- tensor([[1, 8], [1, 81]])

print(tensor_1.pow(tensor_2))
# Outputs- tensor([[1, 8], [1, 81]])

tensor([[ 1,  8],
        [ 1, 81]])
tensor([[ 1,  8],
        [ 1, 81]])


# Remainder
- The remainder operation can be performed using the % operand. This will calculate the remainder of elements in the first tensor after division by respective elements in the second tensor.
- Note: A ZeroDivisionError will be returned if any of the elements in the divisor tensor is 0.

In [15]:
tensor_1 = torch.tensor([[3, 8], [9, 4]])
tensor_2 = torch.tensor([[2, 3], [5, 4]])

print(tensor_1 % tensor_2)
# Outputs- tensor([[1, 2], [4, 0]])

tensor([[1, 2],
        [4, 0]])


In [18]:
tensor_1 = torch.tensor([[1, 2], [1, 3]])
tensor_2 = torch.tensor([[2, 3], [3, 4]])

print(torch.remainder(tensor_1, tensor_2))
# Outputs- tensor([[1, 2], [4, 0]])

print(tensor_1.remainder(tensor_2))
# Outputs- tensor([[1, 2], [4, 0]])

tensor([[1, 2],
        [1, 3]])
tensor([[1, 2],
        [1, 3]])
