In [1]:
import torch

Broadcasting functionality in Pytorch has been borrowed from Numpy. Broadcasting allows the performing of arithmetic operations on tensors that are not of the same size. Pytorch automatically does the broadcasting of the ‘smaller’ tensor to the size of the ‘larger’ tensor, only if certain constraints are met
- https://deeplearninguniversity.com/pytorch/pytorch-broadcasting/

In [2]:
tensor = torch.tensor([1, 2, 3, 4]) + torch.tensor([1, 2, 3])
# Outputs- RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0

In [3]:
tensor = torch.tensor([1, 2, 3])+torch.tensor([1])

print(tensor)
# Outputs- tensor([2, 3, 4])

tensor([2, 3, 4])


# Rules for Broadcasting
Two tensors are compatible for broadcasting only if, when starting from the trailing dimensions of the tensors:

- If the dimensions of both the tensors are the same.
- If the dimension of one of the tensors is 1.

In [4]:
tensor1 = torch.tensor([[1, 2], [0, 3]])
tensor2 = torch.tensor([[3, 1]])
tensor3 = torch.tensor([[5], [2]])
tensor4 = torch.tensor([7])

print(tensor1.shape)
# Outputs- torch.Size([2, 2])
print(tensor2.shape)
# Outputs- torch.Size([1, 2])
print(tensor3.shape)
# Outputs- torch.Size([2, 1])
print(tensor4.shape)
# Outputs- torch.Size([1])

print(tensor1 + tensor2)
# Outputs- tensor([[4, 3], [3, 4]])
print(tensor1 + tensor3)
# Outputs- tensor([[6, 7], [2, 5]])
print(tensor2 + tensor3)
# Outputs- tensor([[8, 6], [5, 3]])
print(tensor1 + tensor4)
# Outputs- tensor([[ 8, 9], [ 7, 10]])

torch.Size([2, 2])
torch.Size([1, 2])
torch.Size([2, 1])
torch.Size([1])
tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])
