In [2]:
import torch

# Absolute

In [3]:
x = torch.tensor([[-1, 4], [-2, 1]])

# Does not make changes to tensor x, stores the result in y
y = torch.abs(x)

print(y)
# Outputs- tensor([[1, 4], [2, 1]])

# abs() function is called directly on the tensor
print(x.abs())
# Outputs- tensor([[1, 4], [2, 1]])

# Changes the original tensor
x.abs_()
print(x)
# Outputs- tensor([[1, 4], [2, 1]])

tensor([[1, 4],
        [2, 1]])
tensor([[1, 4],
        [2, 1]])
tensor([[1, 4],
        [2, 1]])


# Round

In [4]:
x = torch.tensor([[-1.1, 4.7], [-2.9, 1.24]])

# Does not make changes to tensor x, stores the result in y
y = torch.round(x)
print(y)
# Outputs- tensor([[-1., 5.], [-3., 1.]])

# round() function is called directly on the tensor
print(x.round())
# Outputs- tensor([[-1., 5.], [-3., 1.]])

# Changes the original tensor
x.round_()
print(x)
# Outputs- tensor([[-1., 5.], [-3., 1.]])

tensor([[-1.,  5.],
        [-3.,  1.]])
tensor([[-1.,  5.],
        [-3.,  1.]])
tensor([[-1.,  5.],
        [-3.,  1.]])


# Ceil

In [5]:
x = torch.tensor([[-1.1, 4.7], [-2.9, 1.24]])

# Does not make changes to tensor x, stores the result in y
y = torch.ceil(x)
print(y)
# Outputs- tensor([[-1., 5.], [-2., 2.]])

# ceil() function is called directly on the tensor
print(x.ceil())
# Outputs- tensor([[-1., 5.], [-2., 2.]])

# Changes the original tensor
x.ceil_()
print(x)
# Outputs- tensor([[-1., 5.], [-2., 2.]])

tensor([[-1.,  5.],
        [-2.,  2.]])
tensor([[-1.,  5.],
        [-2.,  2.]])
tensor([[-1.,  5.],
        [-2.,  2.]])


# Floor

In [6]:
x = torch.tensor([[-1.1, 4.7], [-2.9, 1.24]])

# Does not make changes to tensor x, stores the result in y
y = torch.floor(x)
print(y)
# Outputs- tensor([[-2., 4.], [-3., 1.]])

# floor() function is called directly on the tensor
print(x.floor())
# Outputs- tensor([[-2., 4.], [-3., 1.]])

# Changes the original tensor
x.floor_()
print(x)
# Outputs- tensor([[-2., 4.], [-3., 1.]])

tensor([[-2.,  4.],
        [-3.,  1.]])
tensor([[-2.,  4.],
        [-3.,  1.]])
tensor([[-2.,  4.],
        [-3.,  1.]])


# Sin

In [7]:
x = torch.tensor([1.0, 2.0, 3.0])

# Does not make changes to tensor x, stores the result in y
y = torch.sin(x)            
print(y)
# Outputs- tensor([0.8415, 0.9093, 0.1411])

# sin() function is called directly on the tensor
print(x.sin())
# Outputs- tensor([0.8415, 0.9093, 0.1411])

# Changes the original tensor
x.sin_()
print(x)
# Outputs- tensor([0.8415, 0.9093, 0.1411])

tensor([0.8415, 0.9093, 0.1411])
tensor([0.8415, 0.9093, 0.1411])
tensor([0.8415, 0.9093, 0.1411])


# Cos

In [8]:
x = torch.tensor([1.0, 2.0, 3.0])

# Does not make changes to tensor x, stores the result in y
y = torch.cos(x)
print(y)
# Outputs- tensor([0.5403, -0.4161, -0.9900])

# cos() function is called directly on the tensor
print(x.cos())
# Outputs- tensor([0.5403, -0.4161, -0.9900])

# Changes the original tensor
x.cos_()
print(x)
# Outputs- tensor([0.5403, -0.4161, -0.9900])

tensor([ 0.5403, -0.4161, -0.9900])
tensor([ 0.5403, -0.4161, -0.9900])
tensor([ 0.5403, -0.4161, -0.9900])


# Square Root

In [9]:
x = torch.tensor([2., 3., 4., 5.])

# Does not make changes to tensor x, stores the result in y
y = torch.sqrt(x)
print(y)
# Outputs- tensor([1.4142, 1.7321, 2.0000, 2.2361])

# sqrt() function is called directly on the tensor
print(x.sqrt())
# Outputs- tensor([1.4142, 1.7321, 2.0000, 2.2361])

# Changes the original tensor
x.sqrt_()
print(x)
# Outputs- tensor([1.4142, 1.7321, 2.0000, 2.2361])

tensor([1.4142, 1.7321, 2.0000, 2.2361])
tensor([1.4142, 1.7321, 2.0000, 2.2361])
tensor([1.4142, 1.7321, 2.0000, 2.2361])


# Natural Logarithm (to the base e)

In [10]:
x = torch.tensor([1.4, 2, 4.0])

# Does not make changes to tensor x, stores the result in y
y = torch.log(x)
print(y)
# Outputs- tensor([0.3365, 0.6931, 1.3863])

# log() function is called directly on the tensor
print(x.log())
# Outputs- tensor([0.5403, -0.4161, -0.9900])

# Changes the original tensor
x.log_()
print(x)
# Outputs- tensor([0.5403, -0.4161, -0.9900])

tensor([0.3365, 0.6931, 1.3863])
tensor([0.3365, 0.6931, 1.3863])
tensor([0.3365, 0.6931, 1.3863])
