In [1]:
import torch

# Mean

In [4]:
x = torch.tensor([[1., 4., 7.], [4., 9., 11.]])
# (1+4+7+4+9+11)/6
print(torch.mean(x))
# Outputs- tensor(6.)

print(x.mean())
# Outputs- tensor(6.)

tensor(6.1667)
tensor(6.1667)


# Median

In [35]:
x = torch.tensor([[1., 1., 4., 5., 6., 7., 8]])
print(torch.median(x))
# Outputs- tensor(5.)

print(x.median())
# Outputs- tensor(5.)

tensor(5.)
tensor(5.)


In [36]:
x = torch.tensor([[1., 1., 4.,], [5., 6., 8]])
print(torch.median(x))
# Outputs- tensor(4.)

print(x.median())
# Outputs- tensor(4.)

tensor(4.)
tensor(4.)


# Mode
torch.mode(x) returns a named tuple of the form (values, indices), where values contains the mode value for each row, and indices contains the index of the occurrence of last mode value in each row.

Yang paling banyak muncul

In [38]:
x = torch.tensor([[1, 4, 7, 1], [11, 11, 7, 1]])

print(torch.mode(x))
# Outputs- torch.return_types.mode(values=tensor([1, 11]), indices=tensor([3, 1]))
# values=tensor([ 1, 11]) Artinya yang paling banyak muncul adalah 1 dan 11
# indices=tensor([3, 1])) Artinya index terakhir yg muncul ada di indeks ke 3 untuk angka 1, dan
# 1 adalah index terkhir yg muncul untuk angka 11
print(x.mode())
# Outputs- torch.return_types.mode(values=tensor([1, 11]), indices=tensor([3, 1]))

torch.return_types.mode(
values=tensor([ 1, 11]),
indices=tensor([3, 1]))
torch.return_types.mode(
values=tensor([ 1, 11]),
indices=tensor([3, 1]))


In [42]:
a = torch.randint(10, (5,))
# tensor([6, 5, 1, 0, 2])
b = a + (torch.randn(50, 1) * 5).long()
torch.mode(b, 0)
# torch.return_types.mode(values=tensor([6, 5, 1, 0, 2]), indices=tensor([2, 2, 2, 2, 2]))

torch.return_types.mode(
values=tensor([5, 2, 0, 6, 0]),
indices=tensor([41, 41, 41, 41, 41]))

In [43]:
torch.mode(a, 0)

torch.return_types.mode(
values=tensor(2),
indices=tensor(4))

# Standard Deviation

In [45]:
# Create a tensor
T = torch.Tensor([2.453, 4.432, 0.754, -6.554])
print("T:", T)
# Compute the mean and standard deviation
mean = torch.mean(T)
std = torch.std(T)

# Print the computed mean and standard deviation
print("Mean:", mean)
print("Standard deviation:", std)

T: tensor([ 2.4530,  4.4320,  0.7540, -6.5540])
Mean: tensor(0.2713)
Standard deviation: tensor(4.7920)


In [46]:
x = torch.tensor([[1., 4., 1.], [11., 9., 11.]])

print(torch.std(x))
# Outputs- tensor(4.7504)

print(x.std())
# Outputs- tensor(4.7504)

tensor(4.7504)
tensor(4.7504)


In [47]:
# create a 3x4 2D tensor
T = torch.Tensor([[2,4,7,-6],
[7,33,-62,23],
[2,-6,-77,54]])
print("T:\n", T)

# compute the mean and standard deviation
mean = torch.mean(T)
std = torch.std(T)
print("Mean:", mean)
print("Standard deviation:", std)

# Compute column-wise mean and std
mean = torch.mean(T, axis = 0)
std = torch.std(T, axis = 0)
print("Column-wise Mean:\n", mean)
print("Column-wise Standard deviation:\n", std)

# Compute row-wise mean and std
mean = torch.mean(T, axis = 1)
std = torch.std(T, axis = 1)
print("Row-wise Mean:\n", mean)
print("Row-wise Standard deviation:\n", std)

T:
 tensor([[  2.,   4.,   7.,  -6.],
        [  7.,  33., -62.,  23.],
        [  2.,  -6., -77.,  54.]])
Mean: tensor(-1.5833)
Standard deviation: tensor(36.2703)
Column-wise Mean:
 tensor([  3.6667,  10.3333, -44.0000,  23.6667])
Column-wise Standard deviation:
 tensor([ 2.8868, 20.2567, 44.7996, 30.0056])
Row-wise Mean:
 tensor([ 1.7500,  0.2500, -6.7500])
Row-wise Standard deviation:
 tensor([ 5.5603, 42.8593, 53.8602])


# Variance

In [50]:
x = torch.tensor([[1., 4., 1.], [11., 9., 11.]])

print(torch.var(x))
# Outputs- tensor(22.5667)

print(x.var())
# Outputs- tensor(22.5667)

tensor(22.5667)
tensor(22.5667)


In [55]:
# https://accurate.id/ekonomi-keuangan/rumus-varians/
x = torch.tensor([670., 765., 780., 820., 735.,])

print(torch.var(x))
# Outputs- tensor(3142.5000)

print(x.var())
# Outputs- tensor(3142.5000)

tensor(3142.5000)
tensor(3142.5000)


In [57]:
x = torch.tensor([65., 55., 70., 85., 90., 75., 80., 75.])

print(torch.var(x))
# Outputs- tensor(124.5536)

print(x.var())
# Outputs- tensor(124.5536)

tensor(124.5536)
tensor(124.5536)


# Product

In [58]:
x = torch.tensor([[1, 4, 1], [11, 9, 11]])

print(torch.prod(x))
# Outputs- tensor(4356)

print(x.prod())
# Outputs- tensor(4356)

tensor(4356)
tensor(4356)


# Max

In [59]:
x = torch.tensor([[1, 4, 1], [11, 9, 11]])

print(torch.max(x))
# Outputs- tensor(11)

print(x.max())
# Outputs- tensor(11)

tensor(11)
tensor(11)


# Min

In [60]:
x = torch.tensor([[1, 4, 1], [11, 9, 11]])

print(torch.min(x))
# Outputs- tensor(1)

print(x.min())
# Outputs- tensor(1)

tensor(1)
tensor(1)
