In [8]:
import torch

https://deeplearninguniversity.com/pytorch/pytorch-matrix-functions/

# Transpose

In [2]:
x = torch.tensor([[1, 2], [3, 4]])

# Does not make changes to tensor x, stores the result in y
y = torch.t(x)

print(y)
# Outputs- tensor([[1, 3], [2, 4]])

print(x.t())
# Ouputs- tensor([[1, 3], [2, 4]])

# Changes the original tensor
x.t_()

print(x)
# Outputs- tensor([[1, 3], [2, 4]])

tensor([[1, 3],
        [2, 4]])
tensor([[1, 3],
        [2, 4]])
tensor([[1, 3],
        [2, 4]])


# Determinant

In [4]:
x = torch.tensor([[1., 2.], [3., 4.]])
y = torch.det(x)

# D = (1x4) - (2x3)

print(y)
# Outputs- tensor(-2.0000)

print(x.det())
# Ouputs- tensor(-2.0000)

tensor(-2.)
tensor(-2.)


# Product

In [6]:
mat_1 = torch.tensor([[4, 1], [2, 3]])
mat_2 = torch.tensor([[2, 1], [5, 1]])

result_mat = torch.matmul(mat_1, mat_2)

# Result = (4x2)+(1x5) (4x1)+(1x1)
#          (2x2)+(3x5) (2x1)+(3x1)

print(result_mat)
# Outputs- tensor([[13, 5], [19, 5]])

tensor([[13,  5],
        [19,  5]])


# Inverse

In [11]:
x = torch.tensor([[1., 2.], [3., 1.]])
inv = torch.inverse(x)

print(inv)
# Outputs- tensor([[-0.2000, 0.4000], [0.6000, -0.2000]])

tensor([[-0.2000,  0.4000],
        [ 0.6000, -0.2000]])


# Dimensions

In [12]:
tensor_1 = torch.tensor([[1, 2], [3, 4]])
print(tensor_1.dim())
# Outputs- 2

tensor_2 = torch.tensor([[[1], [2]], [[3], [4]]])
print(tensor_2.dim())
# Outputs- 3

2
3


# Item
return a scalar

In [16]:
tensor_1 = torch.tensor([4])
tensor_2 = torch.tensor([4, 7, 9])

tensor_1.item()
# Outputs- 4

# tensor_2.item()
# # Outputs- ValueError: only one element tensors can be converted to Python scalars

4

# ndim attribute
Each Pytorch tensor has ndim attribute which will return the number of dimensions of the tensor. ndim is an alias for the dim() function.


In [17]:
tensor_1 = torch.tensor([[1, 2], [3, 4]])
print(tensor_1.ndim)
# Outputs- 2

tensor_2 = torch.tensor([[[1], [2]], [[3], [4]]])
print(tensor_2.ndim)
# Outputs- 3

2
3


# T Attribute
Each Pytorch tensor has T attribute which will return the transpose of the matrix.

In [18]:
x = torch.tensor([[1., 2.], [3., 1.]])
print(x.T)
# Outputs- tensor([[1., 3.], [2., 1.]])

tensor([[1., 3.],
        [2., 1.]])
