In [1]:
import torch

# Random

In [3]:
# This will create a tensor with the shape 2, 3 with random values
tensor_1 = torch.rand(2, 3)

print(tensor_1)
# Outputs- tensor([[0.8823, 0.9150, 0.3829], [0.9593, 0.3904, 0.6009]])

# We can also pass a tuple specifying the desired shape of tensor.
tensor_2 = torch.rand((2, 3))

print(tensor_2)
# Outputs- tensor([[0.2566, 0.7936, 0.9408], [0.1332, 0.9346, 0.5936]]

tensor([[0.7428, 0.4116, 0.9334],
        [0.7482, 0.6508, 0.8269]])
tensor([[0.4464, 0.0078, 0.3407],
        [0.1916, 0.7133, 0.0107]])


# Random Integer

In [4]:
tensor_1 = torch.randint(-10, 10, (4, 5))

print(tensor_1)
# Outputs- tensor([[0, 4, 1, 2, 5], [5, -3, -4, -1, 6]])

tensor([[ -2, -10,  -6,  -6,  -9],
        [  0,   2,  -4,  -4, -10],
        [  0,  -9,   4, -10,  -9],
        [  9, -10,  -8,  -2,   1]])


# Seed

In [6]:
torch.initial_seed()
# Outputs- 16791183524288837558

309584584122700

In [7]:
# sets the seed manually to 42
torch.manual_seed(42)

torch.rand((2, 3))
# Outputs- tensor([[0.8823, 0.9150, 0.3829], [0.9593, 0.3904, 0.6009]])

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [8]:
# This will seed for the random generator with a new seed.
torch.seed()
# Outputs- 15377867763402226090

# The new seed is 15377867763402226090

torch.initial_seed()
# Outputs- 15377867763402226090
# Checking if the value of seed has changed

309694716967000