In [1]:
import torch

# View

In [4]:
tensor_1 = torch.tensor([[1, 2], [3, 4]])
print(tensor_1)

# Create tensor_2 as a view of tensor_1
tensor_2 = tensor_1.view(4, 1)

print(tensor_2)
# Outputs- tensor([[1], [2], [3], [4]])

# Changing data in the original tensor
tensor_1[0][0] = -1

print(tensor_2)
# Outputs- tensor([[-1], [2], [3], [4]])

tensor([[1, 2],
        [3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([[-1],
        [ 2],
        [ 3],
        [ 4]])


In [7]:
tensor_1 = torch.tensor([[1, 2], [3, 4]])

# Storing the transpose of tensor_1 in a new tensor
# This makes the new tensor(tensor_2) non-contiguous
tensor_2 = tensor_1.t()

# print(tensor_2.view(4, 1))
# # Outputs- RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [8]:
tensor_1 = torch.tensor([[1, 2], [3, 4]])

# Storing the transpose of tensor_1 in a new tensor
# This makes the new tensor(tensor_2) non-contiguous
tensor_2 = tensor_1.t()

# tensor_contg is a contiguous tensor created from tensor_2 
tensor_contg = tensor_2.contiguous()

print(tensor_contg.view(4, 1))
# Outputs- tensor([[1], [3], [2], [4]])

tensor([[1],
        [3],
        [2],
        [4]])


# Reshape

In [9]:
tensor_1 = torch.tensor([[1, 2], [3, 4]])

# Create tensor_2 from tensor_1 using reshape() function
tensor_2 = tensor_1.reshape(4, 1)

print(tensor_2)
# Outputs- tensor([[1], [2], [3], [4]])

# Changing data in the original tensor
tensor_1[0][0] = -1

print(tensor_2)
# Outputs- tensor([[-1], [2], [3], [4]])

tensor([[1],
        [2],
        [3],
        [4]])
tensor([[-1],
        [ 2],
        [ 3],
        [ 4]])


In [10]:
tensor_1 = torch.tensor([[1, 2], [3, 4]])

# Storing the transpose of tensor_1 in a new tensor
# This makes the new tensor(tensor_2) non-contiguous
tensor_2 = tensor_1.t()

# Calling the reshape() function on a non-contiguous tensor 
tensor_3 = tensor_2.reshape(4, 1)

# Changing data in the original tensor
tensor_1[0][0] = -1

print(tensor_1)
# Outputs- tensor([[-1,  2], [3,  4]])

print(tensor_3)
# Outputs- tensor([[1], [3], [2], [4]])

tensor([[-1,  2],
        [ 3,  4]])
tensor([[1],
        [3],
        [2],
        [4]])


Difference between reshape() and view()
- https://deeplearninguniversity.com/pytorch/pytorch-tensor-reshaping/

# Permute

In [11]:
# Creating a random tensor to denote a 299*299 RGB image
img_tensor = torch.rand(299, 299, 3)

print(img_tensor.shape)
# Outputs- torch.Size([299, 299, 3])

# Re-arranging the tensor from [height, width, channel] to [channel, height, width]
rearranged_img_tensor=img_tensor.permute(2, 0, 1)

print(rearranged_img_tensor.shape)
# Outputs- torch.Size([3, 299, 299])

torch.Size([299, 299, 3])
torch.Size([3, 299, 299])
