In [2]:
import torch
import numpy as np

# Tensor to Numpy

In [3]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [5]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [7]:
type(b)

numpy.ndarray

In [8]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


# Numpy to Torch

In [10]:
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [12]:
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [13]:
a = a + 1
print(a)
print(b)
print(type(b))

[2. 2. 2. 2. 2.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>
